@echo off
echo Starting Quantitative Finance Analysis Tool (CLI Mode)...
echo Running comprehensive analysis for AAPL, MSFT, GOOGL, TSLA...
python main_app.py --tickers "AAPL,MSFT,GOOGL,TSLA" --analysis all
pause